### PR TITLE
update bibtex

### PR DESCRIPTION
**Pull request by jbytecode**
Due to the JOSS submission: https://github.com/openjournals/joss-reviews/issues/5510

### CODE REVIEW

**Comment by miniufo** [comment]
Thanks @jbytecode for these corrections.  Just wondering what is the special meaning of `{}` in these cases?

**Comment by jbytecode** [comment]
@miniufo - it is about capitalizing the programming names, e.g., python -> Python

**Comment by jbytecode** [comment]
I only changed markdown and bibtex files so the error should not be directly related to the latest changes. your review is completed, so you can correct the error before pumping a new release but not now.

**Comment by jbytecode** [comment]
If you think the problem is about v3.7 of software, you can downgrade the version to get everything fixed

**Pull request merged**
